version: '3.8'
services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - selenium
    environment:
      - DATABASE_URL=sqlite3:///app/db/development.sqlite3
    tty: true
    stdin_open: true

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=sqlite3:///app/db/test.sqlite3

