version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    #image: sqlite:latest
    image: keinos/sqlite3:latest
    volumes:
      - sqlite_data:/var/lib/sqlite/data

volumes:
  sqlite_data:
